#!/usr/bin/env python3
"""flow/drc_report_trim.py

Reduce a `klt drc --format json` response to the stable subset committed as
`layout/logic_tile.drc.json` evidence: verdict fields (status, violation
counts, coverage), and content-addressed provenance (deck/input hashes),
with tool-version fields that change on a toolchain upgrade alone --
without any layout change -- stripped out.

Why strip those: `provenance.klt_version` and `provenance.klayout_version`
are bare tool-version strings, not part of the deck/input content
addressing. Mirrors `flow/par_report_trim.py`'s identical rationale (see
that file's header comment) and `flow/synth.sh`'s "Generated by Yosys
<version>" header-strip -- upgrading klt/KLayout alone should not produce a
spurious diff against the committed report. `klt drc --check --rerun`
already excludes these same fields from its own drift comparison, so
dropping them here does not weaken the freshness check `flow/drc.sh` runs
via `klt drc --check` (cheap mode: input/deck content_hash only).

Everything else -- status, violation_count, rule_counts, violations,
coverage, and the deck/input content hashes -- is retained unchanged.

Usage:
    drc_report_trim.py <response.json> <output.json>
"""

import sys

from _report_trim import run_cli, strip_nested

_DROP_PROVENANCE = ("klt_version", "klayout_version")


def trim(response: dict) -> dict:
    return strip_nested(response, "provenance", _DROP_PROVENANCE)


def main(argv: list) -> int:
    return run_cli(argv, trim)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
