#!/usr/bin/env python3
"""flow/par_report_trim.py

Reduce a `klt place-and-route --format json` response to the stable subset
committed as `layout/logic_tile.par.json` evidence: physical-design metrics
and content-addressed provenance (PDK/deck/input hashes), with every field
that is either a local absolute filesystem path or a bare tool-version
string stripped out.

Why strip those: absolute paths (`def_path`, `gds_path`, `verilog_path`,
`layer_map.path`) point into the invoking machine's own scratch directory
and are never reproducible across machines/checkouts. Tool-version strings
(`engine_version`, `provenance.klt_version`, `provenance.klayout_version`)
change on a toolchain upgrade alone, with no design change involved --
stripping them mirrors `flow/synth.sh`'s own "Generated by Yosys <version>"
header-strip, so upgrading OpenROAD/klt/KLayout alone does not produce a
spurious diff against the committed report. Everything else (die/core area,
utilization, wirelength, slack, violation counts, per-corner results, and
the PDK/deck/input content hashes) is retained unchanged.

Usage:
    par_report_trim.py <response.json> <output.json>
"""

import json
import sys

_DROP_TOP_LEVEL = ("def_path", "gds_path", "verilog_path", "engine_version")
_DROP_LAYER_MAP = ("path",)
_DROP_PROVENANCE = ("klt_version", "klayout_version")


def trim(response: dict) -> dict:
    trimmed = dict(response)
    for key in _DROP_TOP_LEVEL:
        trimmed.pop(key, None)
    if "layer_map" in trimmed and isinstance(trimmed["layer_map"], dict):
        layer_map = dict(trimmed["layer_map"])
        for key in _DROP_LAYER_MAP:
            layer_map.pop(key, None)
        trimmed["layer_map"] = layer_map
    if "provenance" in trimmed and isinstance(trimmed["provenance"], dict):
        provenance = dict(trimmed["provenance"])
        for key in _DROP_PROVENANCE:
            provenance.pop(key, None)
        trimmed["provenance"] = provenance
    return trimmed


def main(argv: list) -> int:
    if len(argv) != 3:
        print(f"usage: {argv[0]} <response.json> <output.json>", file=sys.stderr)
        return 2
    src, dst = argv[1], argv[2]
    with open(src, encoding="utf-8") as f:
        response = json.load(f)
    trimmed = trim(response)
    with open(dst, "w", encoding="utf-8") as f:
        json.dump(trimmed, f, indent=2, sort_keys=True)
        f.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
