#!/usr/bin/env python3
"""flow/par_report_trim.py

Reduce a `klt place-and-route --format json` response to the stable subset
committed as `layout/logic_tile.par.json` evidence: physical-design metrics
and content-addressed provenance (PDK/deck/input hashes), with every field
that is either a local absolute filesystem path or a bare tool-version
string stripped out.

Why strip those: absolute paths (`def_path`, `gds_path`, `verilog_path`,
`layer_map.path`) point into the invoking machine's own scratch directory
and are never reproducible across machines/checkouts. Tool-version strings
(`engine_version`, `provenance.klt_version`, `provenance.klayout_version`)
change on a toolchain upgrade alone, with no design change involved --
stripping them mirrors `flow/synth.sh`'s own "Generated by Yosys <version>"
header-strip, so upgrading OpenROAD/klt/KLayout alone does not produce a
spurious diff against the committed report. Everything else (die/core area,
utilization, wirelength, slack, violation counts, per-corner results, and
the PDK/deck/input content hashes) is retained unchanged.

Usage:
    par_report_trim.py <response.json> <output.json>
"""

import sys

from _report_trim import run_cli, strip_nested

_DROP_TOP_LEVEL = ("def_path", "gds_path", "verilog_path", "engine_version")
_DROP_LAYER_MAP = ("path",)
_DROP_PROVENANCE = ("klt_version", "klayout_version")


def trim(response: dict) -> dict:
    trimmed = dict(response)
    for key in _DROP_TOP_LEVEL:
        trimmed.pop(key, None)
    trimmed = strip_nested(trimmed, "layer_map", _DROP_LAYER_MAP)
    trimmed = strip_nested(trimmed, "provenance", _DROP_PROVENANCE)
    return trimmed


def main(argv: list) -> int:
    return run_cli(argv, trim)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
