#!/usr/bin/env python3
"""flow/sdf_annotate_shim.py

Write the extra, otherwise-empty Verilog elaboration root that carries a
`$sdf_annotate` call, so a real IEEE-1497 SDF can be back-annotated onto a
plain (non-cocotb) Icarus Verilog gate-level simulation.

This mirrors -- deliberately, not by independent reinvention -- the exact
mechanism `klt functional-verification`'s `options.sdf` uses internally
(`_write_sdf_annotate_shim` in klayout-tools'
`src/klayout_tools/functional_verification.py`, issue #1002): `$sdf_annotate`
is a Verilog system task and must be called from an `initial` block inside
some elaborated module, and a conventional testbench's own `initial` block is
busy driving stimulus, so a second, sibling `-s` root carries the call
instead. klayout-tools' own docs (docs/cli/functional-verification.md, "SDF
back-annotation") name this idiom as the one cocotb's own Icarus runner
already uses for waveform-dump modules.

Why this script exists rather than invoking `klt functional-verification`
directly: that verb's `testbench.module` requires a cocotb Python test
module, and `sim/tb_logic_tile.v` is a conventional, self-checking Verilog
testbench that is already its own elaboration root with a free `initial`
block -- so the DUT does not need `klt functional-verification`'s additional
`_write_sdf_dut_wrapper` nesting fix (issue #1056) for a bare top-level-port
`INTERCONNECT` entry; the existing testbench root already provides the
"nested child instance" shape that fix produces synthetically. See
flow/README.md's "SDF-annotated gate-level re-simulation" section for the
full picture, including the upstream crash this design's escaped
identifiers currently trigger.

Usage:
    sdf_annotate_shim.py <output.v> <sdf_path> <scope>

`<sdf_path>` must be absolute -- `vvp` runs with its own working directory,
and a relative path here is one `SDF WARNING` away from a silent zero-delay
run (same requirement `klt functional-verification` enforces). `<scope>` is
the hierarchical Verilog path `$sdf_annotate`'s second argument names (e.g.
`tb_logic_tile.dut`).
"""

from __future__ import annotations

import os
import sys

_SHIM_MODULE_NAME = "klt_sdf_annotate"


def render_shim(sdf_path: str, scope: str) -> str:
    if not os.path.isabs(sdf_path):
        raise ValueError(f"sdf_path must be absolute, got: {sdf_path!r}")
    escaped = sdf_path.replace("\\", "\\\\").replace('"', '\\"')
    return (
        "// Generated by flow/sdf_annotate_shim.py -- do not edit by hand.\n"
        "// Extra elaboration root carrying the $sdf_annotate call, mirroring\n"
        "// klt functional-verification's own _write_sdf_annotate_shim\n"
        "// mechanism (issue #1002).\n"
        f"module {_SHIM_MODULE_NAME}();\n"
        f'  initial $sdf_annotate("{escaped}", {scope});\n'
        "endmodule\n"
    )


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print(f"usage: {argv[0]} <output.v> <sdf_path> <scope>", file=sys.stderr)
        return 1
    output_path, sdf_path, scope = argv[1], argv[2], argv[3]
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(render_shim(sdf_path, scope))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
