#!/usr/bin/env bash
# flow/synth.sh
#
# Derive a generic-cell netlist from the committed tile RTL under
# design/rtl/ via yosys, and check it against the committed copy under
# design/netlist/. This is the reproducibility harness for the second half
# of the T1 "Design sources" pass condition (see
# docs/design-evidence-tiers.md in 2AMLogic/klayout-tools, and issue #7):
# "committed design sources plus the derived netlist, regenerated on design
# change -- presence AND reproducibility, not a one-off drop." Mirrors
# sim/run.sh's "recompile from source every run" pattern -- every run
# re-derives the netlist from source rather than trusting a stale artifact.
#
# This is a plain generic-cell (technology-independent) synthesis pass --
# proc/opt/memory/techmap only, no sky130 standard-cell/liberty mapping.
# Standard-cell mapping and physical design are separate, already-tracked
# work (see design/README.md's "Out of scope here").
#
# Usage:
#   ./flow/synth.sh            # regenerate the netlist and diff it against
#                               # the committed copy under design/netlist/.
#                               # Exit 0 if identical, non-zero if they
#                               # differ (RTL changed but netlist wasn't
#                               # regenerated) or synthesis fails.
#   ./flow/synth.sh --update   # regenerate the netlist and overwrite the
#                               # committed copy under design/netlist/.
#                               # Use this after an intentional RTL change.
#
# Requires yosys on PATH.
#
# Exit status: 0 on success (synthesis succeeded, and in the default mode
# the regenerated netlist matches the committed copy); non-zero otherwise.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RTL_DIR="$REPO_ROOT/design/rtl"
NETLIST_DIR="$REPO_ROOT/design/netlist"
BUILD_DIR="$SCRIPT_DIR/build"
TOP_MODULE="logic_tile"
NETLIST_NAME="logic_tile_netlist.v"

MODE="check"
case "${1:-}" in
    --update)
        MODE="update"
        ;;
    "")
        MODE="check"
        ;;
    *)
        echo "usage: $0 [--update]" >&2
        exit 1
        ;;
esac

if ! command -v yosys >/dev/null 2>&1; then
    echo "error: yosys not found on PATH" >&2
    exit 1
fi

mkdir -p "$BUILD_DIR" "$NETLIST_DIR"

YS_SCRIPT="$BUILD_DIR/synth.ys"
RAW_NETLIST="$BUILD_DIR/${NETLIST_NAME}.raw"
GENERATED_NETLIST="$BUILD_DIR/${NETLIST_NAME}"
COMMITTED_NETLIST="$NETLIST_DIR/${NETLIST_NAME}"

# Generic-cell synthesis: proc/opt/memory/techmap only -- no sky130
# standard-cell/liberty mapping (see header comment above).
cat > "$YS_SCRIPT" <<EOF
read_verilog -sv ${RTL_DIR}/lut4_slice.v
read_verilog -sv ${RTL_DIR}/logic_tile.v
hierarchy -top ${TOP_MODULE}
proc; opt; memory; opt; techmap; opt
stat
write_verilog -noattr ${RAW_NETLIST}
EOF

echo "=== synthesizing ${TOP_MODULE} ==="
if ! yosys -s "$YS_SCRIPT" 2>&1 | tee "$BUILD_DIR/synth.log"; then
    echo "error: yosys synthesis failed (see $BUILD_DIR/synth.log)" >&2
    exit 1
fi

if [[ ! -s "$RAW_NETLIST" ]]; then
    echo "error: yosys did not produce a netlist at $RAW_NETLIST" >&2
    exit 1
fi

# Strip the "Generated by Yosys <version>" header comment so the committed
# netlist doesn't churn on yosys version upgrades alone -- only an actual
# RTL/netlist-shape change should produce a diff.
sed '/^\/\* Generated by Yosys/d' "$RAW_NETLIST" > "$GENERATED_NETLIST"

if [[ "$MODE" == "update" ]]; then
    cp "$GENERATED_NETLIST" "$COMMITTED_NETLIST"
    echo "=== netlist written to ${COMMITTED_NETLIST} ==="
    exit 0
fi

if [[ ! -f "$COMMITTED_NETLIST" ]]; then
    echo "error: no committed netlist at $COMMITTED_NETLIST -- run '$0 --update' to create it" >&2
    exit 1
fi

if ! diff -u "$COMMITTED_NETLIST" "$GENERATED_NETLIST"; then
    echo "error: regenerated netlist differs from the committed copy at $COMMITTED_NETLIST" >&2
    echo "       RTL changed without regenerating the netlist -- run '$0 --update' and commit the result" >&2
    exit 1
fi

echo "=== committed netlist matches regenerated output (reproducible) ==="
