// Differential check: repo switch-matrix RTL (design/rtl/logic_tile_switch_matrix.v,
// generated by design/gen/gen_switch_matrix.py) vs FABulous's generated
// LOGIC4_switch_matrix.v, driven with identical inputs and config bits.
// Issue #96.  Run via flow/fabulous.sh (the FABulous side is generated into
// the gitignored flow/build/ scratch dir, never committed).
//
// Bit-order mapping under test: FABulous tile ConfigBits[157:68] feed the
// switch matrix as its local ConfigBits[89:0]; repo cfg[k] == ConfigBits[68+k].
// Both modules use the same field layout: sinks in .list first-appearance
// order, LSB first: 16 x 3-bit mux-7 fields (N/E/S/W 1BEG0..3) at cfg[3k+:3],
// then 21 x 2-bit mux-4 fields at cfg[48+2m+:2] (L{A..D}_I0..3, then the
// jump-wire muxes); the 0-bit mux-1 sinks (EN/SR) use no bits.
//
// A mux-7 select of 7 (>= fan-in) is defined as 0 by the repo RTL; the FABulous
// array index is out of range and yields X.  Those cases are checked as
// "repo == 0 and FABulous == X", with every other sink still compared.
`timescale 1ns/1ps
module tb;
    reg  [19:0] in;
    reg  [89:0] cfg;
    wire [39:0] REF, FAB;   // ports in repo order; BEG outputs are [15:0]
    wire J_SR, J_EN0, J_EN1, J_EN2, J_EN3;
    integer i, k, t, checks = 0, fails = 0, xchecks = 0;
    reg [39:0] mask;
    reg [89:0] c;

    logic_tile_switch_matrix REF_i (
        .N1END0(in[0]),
        .E1END0(in[1]),
        .S1END0(in[2]),
        .W1END0(in[3]),
        .N1END1(in[4]),
        .E1END1(in[5]),
        .S1END1(in[6]),
        .W1END1(in[7]),
        .N1END2(in[8]),
        .E1END2(in[9]),
        .S1END2(in[10]),
        .W1END2(in[11]),
        .N1END3(in[12]),
        .E1END3(in[13]),
        .S1END3(in[14]),
        .W1END3(in[15]),
        .LA_O(in[16]),
        .LB_O(in[17]),
        .LC_O(in[18]),
        .LD_O(in[19]),
        .N1BEG0(REF[0]),
        .N1BEG1(REF[1]),
        .N1BEG2(REF[2]),
        .N1BEG3(REF[3]),
        .E1BEG0(REF[4]),
        .E1BEG1(REF[5]),
        .E1BEG2(REF[6]),
        .E1BEG3(REF[7]),
        .S1BEG0(REF[8]),
        .S1BEG1(REF[9]),
        .S1BEG2(REF[10]),
        .S1BEG3(REF[11]),
        .W1BEG0(REF[12]),
        .W1BEG1(REF[13]),
        .W1BEG2(REF[14]),
        .W1BEG3(REF[15]),
        .LA_I0(REF[16]),
        .LA_I1(REF[17]),
        .LA_I2(REF[18]),
        .LA_I3(REF[19]),
        .LA_SR(REF[20]),
        .LA_EN(REF[21]),
        .LB_I0(REF[22]),
        .LB_I1(REF[23]),
        .LB_I2(REF[24]),
        .LB_I3(REF[25]),
        .LB_SR(REF[26]),
        .LB_EN(REF[27]),
        .LC_I0(REF[28]),
        .LC_I1(REF[29]),
        .LC_I2(REF[30]),
        .LC_I3(REF[31]),
        .LC_SR(REF[32]),
        .LC_EN(REF[33]),
        .LD_I0(REF[34]),
        .LD_I1(REF[35]),
        .LD_I2(REF[36]),
        .LD_I3(REF[37]),
        .LD_SR(REF[38]),
        .LD_EN(REF[39]),
        .cfg(cfg)
    );

    // FABulous exposes the jump wires as ports; close the BEG->END loop-back
    // here (the repo RTL does it internally).
    LOGIC4_switch_matrix fab_i (
        .N1END0(in[0]),
        .E1END0(in[1]),
        .S1END0(in[2]),
        .W1END0(in[3]),
        .N1END1(in[4]),
        .E1END1(in[5]),
        .S1END1(in[6]),
        .W1END1(in[7]),
        .N1END2(in[8]),
        .E1END2(in[9]),
        .S1END2(in[10]),
        .W1END2(in[11]),
        .N1END3(in[12]),
        .E1END3(in[13]),
        .S1END3(in[14]),
        .W1END3(in[15]),
        .LA_O(in[16]),
        .LB_O(in[17]),
        .LC_O(in[18]),
        .LD_O(in[19]),
        .N1BEG0(FAB[0]),
        .N1BEG1(FAB[1]),
        .N1BEG2(FAB[2]),
        .N1BEG3(FAB[3]),
        .E1BEG0(FAB[4]),
        .E1BEG1(FAB[5]),
        .E1BEG2(FAB[6]),
        .E1BEG3(FAB[7]),
        .S1BEG0(FAB[8]),
        .S1BEG1(FAB[9]),
        .S1BEG2(FAB[10]),
        .S1BEG3(FAB[11]),
        .W1BEG0(FAB[12]),
        .W1BEG1(FAB[13]),
        .W1BEG2(FAB[14]),
        .W1BEG3(FAB[15]),
        .LA_I0(FAB[16]),
        .LA_I1(FAB[17]),
        .LA_I2(FAB[18]),
        .LA_I3(FAB[19]),
        .LA_SR(FAB[20]),
        .LA_EN(FAB[21]),
        .LB_I0(FAB[22]),
        .LB_I1(FAB[23]),
        .LB_I2(FAB[24]),
        .LB_I3(FAB[25]),
        .LB_SR(FAB[26]),
        .LB_EN(FAB[27]),
        .LC_I0(FAB[28]),
        .LC_I1(FAB[29]),
        .LC_I2(FAB[30]),
        .LC_I3(FAB[31]),
        .LC_SR(FAB[32]),
        .LC_EN(FAB[33]),
        .LD_I0(FAB[34]),
        .LD_I1(FAB[35]),
        .LD_I2(FAB[36]),
        .LD_I3(FAB[37]),
        .LD_SR(FAB[38]),
        .LD_EN(FAB[39]),
        .J_SR_BEG0(J_SR), .J_SR_END0(J_SR),
        .J_EN_BEG0(J_EN0), .J_EN_END0(J_EN0),
        .J_EN_BEG1(J_EN1), .J_EN_END1(J_EN1),
        .J_EN_BEG2(J_EN2), .J_EN_END2(J_EN2),
        .J_EN_BEG3(J_EN3), .J_EN_END3(J_EN3),
        .ConfigBits(cfg), .ConfigBits_N(~cfg)
    );

    task compare(input [39:0] skip);
        integer b;
        begin
            for (b = 0; b < 40; b = b + 1)
                if (!skip[b]) begin
                    checks = checks + 1;
                    if (REF[b] !== FAB[b]) begin
                        fails = fails + 1;
                        $display("FAIL[%0d]: output %0d ref=%b fab=%b cfg=%h in=%h", fails, b, REF[b], FAB[b], cfg, in);
                    end
                end
        end
    endtask

    // random config with every mux-7 select forced in range (0..6)
    task rand_cfg_inrange;
        integer m;
        begin
            cfg = {$random, $random, $random};
            for (m = 0; m < 16; m = m + 1)
                if (cfg[3*m +: 3] == 3'd7) cfg[3*m +: 3] = $random & 32'h3;
        end
    endtask

    initial begin
        // phase 1: random in-range configs and inputs, all 40 sinks
        for (t = 0; t < 20000; t = t + 1) begin
            rand_cfg_inrange;
            in = $random;
            #200;
            compare(40'd0);
        end
        // phase 2: exhaustive per-field sweep; each select value of each
        // field (mux-7 incl. 7, mux-4) with random others, random inputs
        for (k = 0; k < 16; k = k + 1)
            for (i = 0; i < 8; i = i + 1)
                for (t = 0; t < 64; t = t + 1) begin
                    rand_cfg_inrange;
                    cfg[3*k +: 3] = i;
                    in = $random;
                    #200;
                    if (i == 7) begin
                        // out-of-range: repo defines 0, FABulous yields X
                        checks = checks + 2; xchecks = xchecks + 1;
                        if (REF[k] !== 1'b0) begin fails = fails + 1; $display("FAIL[%0d]: field %0d sel 7 repo=%b (want 0)", fails, k, REF[k]); end
                        if (FAB[k] !== 1'bx) begin fails = fails + 1; $display("FAIL[%0d]: field %0d sel 7 fab=%b (want x)", fails, k, FAB[k]); end
                        mask = 40'd0; mask[k] = 1'b1;
                        compare(mask);
                    end else compare(40'd0);
                end
        for (k = 0; k < 21; k = k + 1)
            for (i = 0; i < 4; i = i + 1)
                for (t = 0; t < 64; t = t + 1) begin
                    rand_cfg_inrange;
                    cfg[48 + 2*k +: 2] = i;
                    in = $random;
                    #200;
                    compare(40'd0);
                end
        if (fails == 0)
            $display("PASS: switch_matrix_fabulous_equiv -- %0d checks (%0d select>=fan-in cases: repo==0, FABulous==X), 0 failures", checks, xchecks);
        else
            $display("FAIL: switch_matrix_fabulous_equiv -- %0d checks, %0d failures", checks, fails);
        $finish;
    end
endmodule
