// GENERATED by design/gen/gen_switch_matrix.py from
// design/fabulous/Tile/LOGIC4/LOGIC4_switch_matrix.list -- DO NOT EDIT.
// Regenerate: python3 design/gen/gen_switch_matrix.py \
//   design/fabulous/Tile/LOGIC4/LOGIC4_switch_matrix.list \
//   design/rtl/logic_tile_switch_matrix.v
//
// Combinational LOGIC4 switch matrix: 45 sinks, 90 config bits.
// Per-sink select field position/width/sources are listed below; a
// select value >= fan-in drives 0.  No timing is claimed.

`default_nettype none
`timescale 1ns/1ps

module logic_tile_switch_matrix (
    input  wire [89:0] cfg,
    input  wire N1END0,
    input  wire N1END1,
    input  wire N1END2,
    input  wire N1END3,
    input  wire E1END0,
    input  wire E1END1,
    input  wire E1END2,
    input  wire E1END3,
    input  wire S1END0,
    input  wire S1END1,
    input  wire S1END2,
    input  wire S1END3,
    input  wire W1END0,
    input  wire W1END1,
    input  wire W1END2,
    input  wire W1END3,
    input  wire LA_O,
    input  wire LB_O,
    input  wire LC_O,
    input  wire LD_O,
    output wire N1BEG0,
    output wire N1BEG1,
    output wire N1BEG2,
    output wire N1BEG3,
    output wire E1BEG0,
    output wire E1BEG1,
    output wire E1BEG2,
    output wire E1BEG3,
    output wire S1BEG0,
    output wire S1BEG1,
    output wire S1BEG2,
    output wire S1BEG3,
    output wire W1BEG0,
    output wire W1BEG1,
    output wire W1BEG2,
    output wire W1BEG3,
    output wire LA_I0,
    output wire LA_I1,
    output wire LA_I2,
    output wire LA_I3,
    output wire LA_SR,
    output wire LA_EN,
    output wire LB_I0,
    output wire LB_I1,
    output wire LB_I2,
    output wire LB_I3,
    output wire LB_SR,
    output wire LB_EN,
    output wire LC_I0,
    output wire LC_I1,
    output wire LC_I2,
    output wire LC_I3,
    output wire LC_SR,
    output wire LC_EN,
    output wire LD_I0,
    output wire LD_I1,
    output wire LD_I2,
    output wire LD_I3,
    output wire LD_SR,
    output wire LD_EN
);

    wire J_EN_BEG0;
    wire J_EN_BEG1;
    wire J_EN_BEG2;
    wire J_EN_BEG3;
    wire J_EN_END0;
    wire J_EN_END1;
    wire J_EN_END2;
    wire J_EN_END3;
    wire J_SR_BEG0;
    wire J_SR_END0;
    assign J_EN_END0 = J_EN_BEG0;
    assign J_EN_END1 = J_EN_BEG1;
    assign J_EN_END2 = J_EN_BEG2;
    assign J_EN_END3 = J_EN_BEG3;
    assign J_SR_END0 = J_SR_BEG0;

    // N1BEG0: fan-in 7, cfg[2:0]
    reg N1BEG0_r;
    always @* begin
        case (cfg[2:0])
            3'd0: N1BEG0_r = E1END0;
            3'd1: N1BEG0_r = S1END0;
            3'd2: N1BEG0_r = W1END0;
            3'd3: N1BEG0_r = LA_O;
            3'd4: N1BEG0_r = LB_O;
            3'd5: N1BEG0_r = LC_O;
            3'd6: N1BEG0_r = LD_O;
            default: N1BEG0_r = 1'b0;
        endcase
    end
    assign N1BEG0 = N1BEG0_r;
    // N1BEG1: fan-in 7, cfg[5:3]
    reg N1BEG1_r;
    always @* begin
        case (cfg[5:3])
            3'd0: N1BEG1_r = E1END1;
            3'd1: N1BEG1_r = S1END1;
            3'd2: N1BEG1_r = W1END1;
            3'd3: N1BEG1_r = LA_O;
            3'd4: N1BEG1_r = LB_O;
            3'd5: N1BEG1_r = LC_O;
            3'd6: N1BEG1_r = LD_O;
            default: N1BEG1_r = 1'b0;
        endcase
    end
    assign N1BEG1 = N1BEG1_r;
    // N1BEG2: fan-in 7, cfg[8:6]
    reg N1BEG2_r;
    always @* begin
        case (cfg[8:6])
            3'd0: N1BEG2_r = E1END2;
            3'd1: N1BEG2_r = S1END2;
            3'd2: N1BEG2_r = W1END2;
            3'd3: N1BEG2_r = LA_O;
            3'd4: N1BEG2_r = LB_O;
            3'd5: N1BEG2_r = LC_O;
            3'd6: N1BEG2_r = LD_O;
            default: N1BEG2_r = 1'b0;
        endcase
    end
    assign N1BEG2 = N1BEG2_r;
    // N1BEG3: fan-in 7, cfg[11:9]
    reg N1BEG3_r;
    always @* begin
        case (cfg[11:9])
            3'd0: N1BEG3_r = E1END3;
            3'd1: N1BEG3_r = S1END3;
            3'd2: N1BEG3_r = W1END3;
            3'd3: N1BEG3_r = LA_O;
            3'd4: N1BEG3_r = LB_O;
            3'd5: N1BEG3_r = LC_O;
            3'd6: N1BEG3_r = LD_O;
            default: N1BEG3_r = 1'b0;
        endcase
    end
    assign N1BEG3 = N1BEG3_r;
    // E1BEG0: fan-in 7, cfg[14:12]
    reg E1BEG0_r;
    always @* begin
        case (cfg[14:12])
            3'd0: E1BEG0_r = N1END0;
            3'd1: E1BEG0_r = S1END0;
            3'd2: E1BEG0_r = W1END0;
            3'd3: E1BEG0_r = LA_O;
            3'd4: E1BEG0_r = LB_O;
            3'd5: E1BEG0_r = LC_O;
            3'd6: E1BEG0_r = LD_O;
            default: E1BEG0_r = 1'b0;
        endcase
    end
    assign E1BEG0 = E1BEG0_r;
    // E1BEG1: fan-in 7, cfg[17:15]
    reg E1BEG1_r;
    always @* begin
        case (cfg[17:15])
            3'd0: E1BEG1_r = N1END1;
            3'd1: E1BEG1_r = S1END1;
            3'd2: E1BEG1_r = W1END1;
            3'd3: E1BEG1_r = LA_O;
            3'd4: E1BEG1_r = LB_O;
            3'd5: E1BEG1_r = LC_O;
            3'd6: E1BEG1_r = LD_O;
            default: E1BEG1_r = 1'b0;
        endcase
    end
    assign E1BEG1 = E1BEG1_r;
    // E1BEG2: fan-in 7, cfg[20:18]
    reg E1BEG2_r;
    always @* begin
        case (cfg[20:18])
            3'd0: E1BEG2_r = N1END2;
            3'd1: E1BEG2_r = S1END2;
            3'd2: E1BEG2_r = W1END2;
            3'd3: E1BEG2_r = LA_O;
            3'd4: E1BEG2_r = LB_O;
            3'd5: E1BEG2_r = LC_O;
            3'd6: E1BEG2_r = LD_O;
            default: E1BEG2_r = 1'b0;
        endcase
    end
    assign E1BEG2 = E1BEG2_r;
    // E1BEG3: fan-in 7, cfg[23:21]
    reg E1BEG3_r;
    always @* begin
        case (cfg[23:21])
            3'd0: E1BEG3_r = N1END3;
            3'd1: E1BEG3_r = S1END3;
            3'd2: E1BEG3_r = W1END3;
            3'd3: E1BEG3_r = LA_O;
            3'd4: E1BEG3_r = LB_O;
            3'd5: E1BEG3_r = LC_O;
            3'd6: E1BEG3_r = LD_O;
            default: E1BEG3_r = 1'b0;
        endcase
    end
    assign E1BEG3 = E1BEG3_r;
    // S1BEG0: fan-in 7, cfg[26:24]
    reg S1BEG0_r;
    always @* begin
        case (cfg[26:24])
            3'd0: S1BEG0_r = N1END0;
            3'd1: S1BEG0_r = E1END0;
            3'd2: S1BEG0_r = W1END0;
            3'd3: S1BEG0_r = LA_O;
            3'd4: S1BEG0_r = LB_O;
            3'd5: S1BEG0_r = LC_O;
            3'd6: S1BEG0_r = LD_O;
            default: S1BEG0_r = 1'b0;
        endcase
    end
    assign S1BEG0 = S1BEG0_r;
    // S1BEG1: fan-in 7, cfg[29:27]
    reg S1BEG1_r;
    always @* begin
        case (cfg[29:27])
            3'd0: S1BEG1_r = N1END1;
            3'd1: S1BEG1_r = E1END1;
            3'd2: S1BEG1_r = W1END1;
            3'd3: S1BEG1_r = LA_O;
            3'd4: S1BEG1_r = LB_O;
            3'd5: S1BEG1_r = LC_O;
            3'd6: S1BEG1_r = LD_O;
            default: S1BEG1_r = 1'b0;
        endcase
    end
    assign S1BEG1 = S1BEG1_r;
    // S1BEG2: fan-in 7, cfg[32:30]
    reg S1BEG2_r;
    always @* begin
        case (cfg[32:30])
            3'd0: S1BEG2_r = N1END2;
            3'd1: S1BEG2_r = E1END2;
            3'd2: S1BEG2_r = W1END2;
            3'd3: S1BEG2_r = LA_O;
            3'd4: S1BEG2_r = LB_O;
            3'd5: S1BEG2_r = LC_O;
            3'd6: S1BEG2_r = LD_O;
            default: S1BEG2_r = 1'b0;
        endcase
    end
    assign S1BEG2 = S1BEG2_r;
    // S1BEG3: fan-in 7, cfg[35:33]
    reg S1BEG3_r;
    always @* begin
        case (cfg[35:33])
            3'd0: S1BEG3_r = N1END3;
            3'd1: S1BEG3_r = E1END3;
            3'd2: S1BEG3_r = W1END3;
            3'd3: S1BEG3_r = LA_O;
            3'd4: S1BEG3_r = LB_O;
            3'd5: S1BEG3_r = LC_O;
            3'd6: S1BEG3_r = LD_O;
            default: S1BEG3_r = 1'b0;
        endcase
    end
    assign S1BEG3 = S1BEG3_r;
    // W1BEG0: fan-in 7, cfg[38:36]
    reg W1BEG0_r;
    always @* begin
        case (cfg[38:36])
            3'd0: W1BEG0_r = N1END0;
            3'd1: W1BEG0_r = E1END0;
            3'd2: W1BEG0_r = S1END0;
            3'd3: W1BEG0_r = LA_O;
            3'd4: W1BEG0_r = LB_O;
            3'd5: W1BEG0_r = LC_O;
            3'd6: W1BEG0_r = LD_O;
            default: W1BEG0_r = 1'b0;
        endcase
    end
    assign W1BEG0 = W1BEG0_r;
    // W1BEG1: fan-in 7, cfg[41:39]
    reg W1BEG1_r;
    always @* begin
        case (cfg[41:39])
            3'd0: W1BEG1_r = N1END1;
            3'd1: W1BEG1_r = E1END1;
            3'd2: W1BEG1_r = S1END1;
            3'd3: W1BEG1_r = LA_O;
            3'd4: W1BEG1_r = LB_O;
            3'd5: W1BEG1_r = LC_O;
            3'd6: W1BEG1_r = LD_O;
            default: W1BEG1_r = 1'b0;
        endcase
    end
    assign W1BEG1 = W1BEG1_r;
    // W1BEG2: fan-in 7, cfg[44:42]
    reg W1BEG2_r;
    always @* begin
        case (cfg[44:42])
            3'd0: W1BEG2_r = N1END2;
            3'd1: W1BEG2_r = E1END2;
            3'd2: W1BEG2_r = S1END2;
            3'd3: W1BEG2_r = LA_O;
            3'd4: W1BEG2_r = LB_O;
            3'd5: W1BEG2_r = LC_O;
            3'd6: W1BEG2_r = LD_O;
            default: W1BEG2_r = 1'b0;
        endcase
    end
    assign W1BEG2 = W1BEG2_r;
    // W1BEG3: fan-in 7, cfg[47:45]
    reg W1BEG3_r;
    always @* begin
        case (cfg[47:45])
            3'd0: W1BEG3_r = N1END3;
            3'd1: W1BEG3_r = E1END3;
            3'd2: W1BEG3_r = S1END3;
            3'd3: W1BEG3_r = LA_O;
            3'd4: W1BEG3_r = LB_O;
            3'd5: W1BEG3_r = LC_O;
            3'd6: W1BEG3_r = LD_O;
            default: W1BEG3_r = 1'b0;
        endcase
    end
    assign W1BEG3 = W1BEG3_r;
    // LA_I0: fan-in 4, cfg[49:48]
    reg LA_I0_r;
    always @* begin
        case (cfg[49:48])
            2'd0: LA_I0_r = N1END0;
            2'd1: LA_I0_r = E1END0;
            2'd2: LA_I0_r = S1END0;
            2'd3: LA_I0_r = W1END0;
            default: LA_I0_r = 1'b0;
        endcase
    end
    assign LA_I0 = LA_I0_r;
    // LA_I1: fan-in 4, cfg[51:50]
    reg LA_I1_r;
    always @* begin
        case (cfg[51:50])
            2'd0: LA_I1_r = N1END1;
            2'd1: LA_I1_r = E1END1;
            2'd2: LA_I1_r = S1END1;
            2'd3: LA_I1_r = W1END1;
            default: LA_I1_r = 1'b0;
        endcase
    end
    assign LA_I1 = LA_I1_r;
    // LA_I2: fan-in 4, cfg[53:52]
    reg LA_I2_r;
    always @* begin
        case (cfg[53:52])
            2'd0: LA_I2_r = N1END2;
            2'd1: LA_I2_r = E1END2;
            2'd2: LA_I2_r = S1END2;
            2'd3: LA_I2_r = W1END2;
            default: LA_I2_r = 1'b0;
        endcase
    end
    assign LA_I2 = LA_I2_r;
    // LA_I3: fan-in 4, cfg[55:54]
    reg LA_I3_r;
    always @* begin
        case (cfg[55:54])
            2'd0: LA_I3_r = N1END3;
            2'd1: LA_I3_r = E1END3;
            2'd2: LA_I3_r = S1END3;
            2'd3: LA_I3_r = W1END3;
            default: LA_I3_r = 1'b0;
        endcase
    end
    assign LA_I3 = LA_I3_r;
    // LA_SR: fan-in 1, cfg[none]
    assign LA_SR = J_SR_END0;
    // LA_EN: fan-in 1, cfg[none]
    assign LA_EN = J_EN_END0;
    // LB_I0: fan-in 4, cfg[57:56]
    reg LB_I0_r;
    always @* begin
        case (cfg[57:56])
            2'd0: LB_I0_r = N1END0;
            2'd1: LB_I0_r = E1END0;
            2'd2: LB_I0_r = S1END0;
            2'd3: LB_I0_r = W1END0;
            default: LB_I0_r = 1'b0;
        endcase
    end
    assign LB_I0 = LB_I0_r;
    // LB_I1: fan-in 4, cfg[59:58]
    reg LB_I1_r;
    always @* begin
        case (cfg[59:58])
            2'd0: LB_I1_r = N1END1;
            2'd1: LB_I1_r = E1END1;
            2'd2: LB_I1_r = S1END1;
            2'd3: LB_I1_r = W1END1;
            default: LB_I1_r = 1'b0;
        endcase
    end
    assign LB_I1 = LB_I1_r;
    // LB_I2: fan-in 4, cfg[61:60]
    reg LB_I2_r;
    always @* begin
        case (cfg[61:60])
            2'd0: LB_I2_r = N1END2;
            2'd1: LB_I2_r = E1END2;
            2'd2: LB_I2_r = S1END2;
            2'd3: LB_I2_r = W1END2;
            default: LB_I2_r = 1'b0;
        endcase
    end
    assign LB_I2 = LB_I2_r;
    // LB_I3: fan-in 4, cfg[63:62]
    reg LB_I3_r;
    always @* begin
        case (cfg[63:62])
            2'd0: LB_I3_r = N1END3;
            2'd1: LB_I3_r = E1END3;
            2'd2: LB_I3_r = S1END3;
            2'd3: LB_I3_r = W1END3;
            default: LB_I3_r = 1'b0;
        endcase
    end
    assign LB_I3 = LB_I3_r;
    // LB_SR: fan-in 1, cfg[none]
    assign LB_SR = J_SR_END0;
    // LB_EN: fan-in 1, cfg[none]
    assign LB_EN = J_EN_END1;
    // LC_I0: fan-in 4, cfg[65:64]
    reg LC_I0_r;
    always @* begin
        case (cfg[65:64])
            2'd0: LC_I0_r = N1END0;
            2'd1: LC_I0_r = E1END0;
            2'd2: LC_I0_r = S1END0;
            2'd3: LC_I0_r = W1END0;
            default: LC_I0_r = 1'b0;
        endcase
    end
    assign LC_I0 = LC_I0_r;
    // LC_I1: fan-in 4, cfg[67:66]
    reg LC_I1_r;
    always @* begin
        case (cfg[67:66])
            2'd0: LC_I1_r = N1END1;
            2'd1: LC_I1_r = E1END1;
            2'd2: LC_I1_r = S1END1;
            2'd3: LC_I1_r = W1END1;
            default: LC_I1_r = 1'b0;
        endcase
    end
    assign LC_I1 = LC_I1_r;
    // LC_I2: fan-in 4, cfg[69:68]
    reg LC_I2_r;
    always @* begin
        case (cfg[69:68])
            2'd0: LC_I2_r = N1END2;
            2'd1: LC_I2_r = E1END2;
            2'd2: LC_I2_r = S1END2;
            2'd3: LC_I2_r = W1END2;
            default: LC_I2_r = 1'b0;
        endcase
    end
    assign LC_I2 = LC_I2_r;
    // LC_I3: fan-in 4, cfg[71:70]
    reg LC_I3_r;
    always @* begin
        case (cfg[71:70])
            2'd0: LC_I3_r = N1END3;
            2'd1: LC_I3_r = E1END3;
            2'd2: LC_I3_r = S1END3;
            2'd3: LC_I3_r = W1END3;
            default: LC_I3_r = 1'b0;
        endcase
    end
    assign LC_I3 = LC_I3_r;
    // LC_SR: fan-in 1, cfg[none]
    assign LC_SR = J_SR_END0;
    // LC_EN: fan-in 1, cfg[none]
    assign LC_EN = J_EN_END2;
    // LD_I0: fan-in 4, cfg[73:72]
    reg LD_I0_r;
    always @* begin
        case (cfg[73:72])
            2'd0: LD_I0_r = N1END0;
            2'd1: LD_I0_r = E1END0;
            2'd2: LD_I0_r = S1END0;
            2'd3: LD_I0_r = W1END0;
            default: LD_I0_r = 1'b0;
        endcase
    end
    assign LD_I0 = LD_I0_r;
    // LD_I1: fan-in 4, cfg[75:74]
    reg LD_I1_r;
    always @* begin
        case (cfg[75:74])
            2'd0: LD_I1_r = N1END1;
            2'd1: LD_I1_r = E1END1;
            2'd2: LD_I1_r = S1END1;
            2'd3: LD_I1_r = W1END1;
            default: LD_I1_r = 1'b0;
        endcase
    end
    assign LD_I1 = LD_I1_r;
    // LD_I2: fan-in 4, cfg[77:76]
    reg LD_I2_r;
    always @* begin
        case (cfg[77:76])
            2'd0: LD_I2_r = N1END2;
            2'd1: LD_I2_r = E1END2;
            2'd2: LD_I2_r = S1END2;
            2'd3: LD_I2_r = W1END2;
            default: LD_I2_r = 1'b0;
        endcase
    end
    assign LD_I2 = LD_I2_r;
    // LD_I3: fan-in 4, cfg[79:78]
    reg LD_I3_r;
    always @* begin
        case (cfg[79:78])
            2'd0: LD_I3_r = N1END3;
            2'd1: LD_I3_r = E1END3;
            2'd2: LD_I3_r = S1END3;
            2'd3: LD_I3_r = W1END3;
            default: LD_I3_r = 1'b0;
        endcase
    end
    assign LD_I3 = LD_I3_r;
    // LD_SR: fan-in 1, cfg[none]
    assign LD_SR = J_SR_END0;
    // LD_EN: fan-in 1, cfg[none]
    assign LD_EN = J_EN_END3;
    // J_SR_BEG0: fan-in 4, cfg[81:80]
    reg J_SR_BEG0_r;
    always @* begin
        case (cfg[81:80])
            2'd0: J_SR_BEG0_r = N1END0;
            2'd1: J_SR_BEG0_r = E1END0;
            2'd2: J_SR_BEG0_r = S1END0;
            2'd3: J_SR_BEG0_r = W1END0;
            default: J_SR_BEG0_r = 1'b0;
        endcase
    end
    assign J_SR_BEG0 = J_SR_BEG0_r;
    // J_EN_BEG0: fan-in 4, cfg[83:82]
    reg J_EN_BEG0_r;
    always @* begin
        case (cfg[83:82])
            2'd0: J_EN_BEG0_r = N1END0;
            2'd1: J_EN_BEG0_r = E1END0;
            2'd2: J_EN_BEG0_r = S1END0;
            2'd3: J_EN_BEG0_r = W1END0;
            default: J_EN_BEG0_r = 1'b0;
        endcase
    end
    assign J_EN_BEG0 = J_EN_BEG0_r;
    // J_EN_BEG1: fan-in 4, cfg[85:84]
    reg J_EN_BEG1_r;
    always @* begin
        case (cfg[85:84])
            2'd0: J_EN_BEG1_r = N1END1;
            2'd1: J_EN_BEG1_r = E1END1;
            2'd2: J_EN_BEG1_r = S1END1;
            2'd3: J_EN_BEG1_r = W1END1;
            default: J_EN_BEG1_r = 1'b0;
        endcase
    end
    assign J_EN_BEG1 = J_EN_BEG1_r;
    // J_EN_BEG2: fan-in 4, cfg[87:86]
    reg J_EN_BEG2_r;
    always @* begin
        case (cfg[87:86])
            2'd0: J_EN_BEG2_r = N1END2;
            2'd1: J_EN_BEG2_r = E1END2;
            2'd2: J_EN_BEG2_r = S1END2;
            2'd3: J_EN_BEG2_r = W1END2;
            default: J_EN_BEG2_r = 1'b0;
        endcase
    end
    assign J_EN_BEG2 = J_EN_BEG2_r;
    // J_EN_BEG3: fan-in 4, cfg[89:88]
    reg J_EN_BEG3_r;
    always @* begin
        case (cfg[89:88])
            2'd0: J_EN_BEG3_r = N1END3;
            2'd1: J_EN_BEG3_r = E1END3;
            2'd2: J_EN_BEG3_r = S1END3;
            2'd3: J_EN_BEG3_r = W1END3;
            default: J_EN_BEG3_r = 1'b0;
        endcase
    end
    assign J_EN_BEG3 = J_EN_BEG3_r;

endmodule

`default_nettype wire
