/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, GNU /usr/bin/c++ 13.3.0) */

module logic_tile_routed(clk, cfg, n_in, e_in, s_in, w_in, n_out, e_out, s_out, w_out);
  input clk;
  wire clk;
  input [157:0] cfg;
  wire [157:0] cfg;
  input [3:0] n_in;
  wire [3:0] n_in;
  input [3:0] e_in;
  wire [3:0] e_in;
  input [3:0] s_in;
  wire [3:0] s_in;
  input [3:0] w_in;
  wire [3:0] w_in;
  output [3:0] n_out;
  wire [3:0] n_out;
  output [3:0] e_out;
  wire [3:0] e_out;
  output [3:0] s_out;
  wire [3:0] s_out;
  output [3:0] w_out;
  wire [3:0] w_out;
  wire [3:0] bel_en;
  wire [3:0] bel_o;
  wire [3:0] bel_sr;
  wire [15:0] lut_in;
  lut4_slice \g_slice[0].u_slice  (
    .ce(bel_en[0]),
    .clk(clk),
    .in(lut_in[3:0]),
    .lut_init(cfg[15:0]),
    .out(bel_o[0]),
    .reg_sel(cfg[16]),
    .rst(bel_sr[0])
  );
  lut4_slice \g_slice[1].u_slice  (
    .ce(bel_en[1]),
    .clk(clk),
    .in(lut_in[7:4]),
    .lut_init(cfg[32:17]),
    .out(bel_o[1]),
    .reg_sel(cfg[33]),
    .rst(bel_sr[1])
  );
  lut4_slice \g_slice[2].u_slice  (
    .ce(bel_en[2]),
    .clk(clk),
    .in(lut_in[11:8]),
    .lut_init(cfg[49:34]),
    .out(bel_o[2]),
    .reg_sel(cfg[50]),
    .rst(bel_sr[2])
  );
  lut4_slice \g_slice[3].u_slice  (
    .ce(bel_en[3]),
    .clk(clk),
    .in(lut_in[15:12]),
    .lut_init(cfg[66:51]),
    .out(bel_o[3]),
    .reg_sel(cfg[67]),
    .rst(bel_sr[3])
  );
  logic_tile_switch_matrix u_sm (
    .E1BEG0(e_out[0]),
    .E1BEG1(e_out[1]),
    .E1BEG2(e_out[2]),
    .E1BEG3(e_out[3]),
    .E1END0(e_in[0]),
    .E1END1(e_in[1]),
    .E1END2(e_in[2]),
    .E1END3(e_in[3]),
    .LA_EN(bel_en[0]),
    .LA_I0(lut_in[0]),
    .LA_I1(lut_in[1]),
    .LA_I2(lut_in[2]),
    .LA_I3(lut_in[3]),
    .LA_O(bel_o[0]),
    .LA_SR(bel_sr[0]),
    .LB_EN(bel_en[1]),
    .LB_I0(lut_in[4]),
    .LB_I1(lut_in[5]),
    .LB_I2(lut_in[6]),
    .LB_I3(lut_in[7]),
    .LB_O(bel_o[1]),
    .LB_SR(bel_sr[1]),
    .LC_EN(bel_en[2]),
    .LC_I0(lut_in[8]),
    .LC_I1(lut_in[9]),
    .LC_I2(lut_in[10]),
    .LC_I3(lut_in[11]),
    .LC_O(bel_o[2]),
    .LC_SR(bel_sr[2]),
    .LD_EN(bel_en[3]),
    .LD_I0(lut_in[12]),
    .LD_I1(lut_in[13]),
    .LD_I2(lut_in[14]),
    .LD_I3(lut_in[15]),
    .LD_O(bel_o[3]),
    .LD_SR(bel_sr[3]),
    .N1BEG0(n_out[0]),
    .N1BEG1(n_out[1]),
    .N1BEG2(n_out[2]),
    .N1BEG3(n_out[3]),
    .N1END0(n_in[0]),
    .N1END1(n_in[1]),
    .N1END2(n_in[2]),
    .N1END3(n_in[3]),
    .S1BEG0(s_out[0]),
    .S1BEG1(s_out[1]),
    .S1BEG2(s_out[2]),
    .S1BEG3(s_out[3]),
    .S1END0(s_in[0]),
    .S1END1(s_in[1]),
    .S1END2(s_in[2]),
    .S1END3(s_in[3]),
    .W1BEG0(w_out[0]),
    .W1BEG1(w_out[1]),
    .W1BEG2(w_out[2]),
    .W1BEG3(w_out[3]),
    .W1END0(w_in[0]),
    .W1END1(w_in[1]),
    .W1END2(w_in[2]),
    .W1END3(w_in[3]),
    .cfg(cfg[157:68])
  );
endmodule

module logic_tile_switch_matrix(cfg, N1END0, N1END1, N1END2, N1END3, E1END0, E1END1, E1END2, E1END3, S1END0, S1END1, S1END2, S1END3, W1END0, W1END1, W1END2, W1END3, LA_O, LB_O, LC_O, LD_O
, N1BEG0, N1BEG1, N1BEG2, N1BEG3, E1BEG0, E1BEG1, E1BEG2, E1BEG3, S1BEG0, S1BEG1, S1BEG2, S1BEG3, W1BEG0, W1BEG1, W1BEG2, W1BEG3, LA_I0, LA_I1, LA_I2, LA_I3, LA_SR
, LA_EN, LB_I0, LB_I1, LB_I2, LB_I3, LB_SR, LB_EN, LC_I0, LC_I1, LC_I2, LC_I3, LC_SR, LC_EN, LD_I0, LD_I1, LD_I2, LD_I3, LD_SR, LD_EN);
  input [89:0] cfg;
  wire [89:0] cfg;
  input N1END0;
  wire N1END0;
  input N1END1;
  wire N1END1;
  input N1END2;
  wire N1END2;
  input N1END3;
  wire N1END3;
  input E1END0;
  wire E1END0;
  input E1END1;
  wire E1END1;
  input E1END2;
  wire E1END2;
  input E1END3;
  wire E1END3;
  input S1END0;
  wire S1END0;
  input S1END1;
  wire S1END1;
  input S1END2;
  wire S1END2;
  input S1END3;
  wire S1END3;
  input W1END0;
  wire W1END0;
  input W1END1;
  wire W1END1;
  input W1END2;
  wire W1END2;
  input W1END3;
  wire W1END3;
  input LA_O;
  wire LA_O;
  input LB_O;
  wire LB_O;
  input LC_O;
  wire LC_O;
  input LD_O;
  wire LD_O;
  output N1BEG0;
  wire N1BEG0;
  output N1BEG1;
  wire N1BEG1;
  output N1BEG2;
  wire N1BEG2;
  output N1BEG3;
  wire N1BEG3;
  output E1BEG0;
  wire E1BEG0;
  output E1BEG1;
  wire E1BEG1;
  output E1BEG2;
  wire E1BEG2;
  output E1BEG3;
  wire E1BEG3;
  output S1BEG0;
  wire S1BEG0;
  output S1BEG1;
  wire S1BEG1;
  output S1BEG2;
  wire S1BEG2;
  output S1BEG3;
  wire S1BEG3;
  output W1BEG0;
  wire W1BEG0;
  output W1BEG1;
  wire W1BEG1;
  output W1BEG2;
  wire W1BEG2;
  output W1BEG3;
  wire W1BEG3;
  output LA_I0;
  wire LA_I0;
  output LA_I1;
  wire LA_I1;
  output LA_I2;
  wire LA_I2;
  output LA_I3;
  wire LA_I3;
  output LA_SR;
  wire LA_SR;
  output LA_EN;
  wire LA_EN;
  output LB_I0;
  wire LB_I0;
  output LB_I1;
  wire LB_I1;
  output LB_I2;
  wire LB_I2;
  output LB_I3;
  wire LB_I3;
  output LB_SR;
  wire LB_SR;
  output LB_EN;
  wire LB_EN;
  output LC_I0;
  wire LC_I0;
  output LC_I1;
  wire LC_I1;
  output LC_I2;
  wire LC_I2;
  output LC_I3;
  wire LC_I3;
  output LC_SR;
  wire LC_SR;
  output LC_EN;
  wire LC_EN;
  output LD_I0;
  wire LD_I0;
  output LD_I1;
  wire LD_I1;
  output LD_I2;
  wire LD_I2;
  output LD_I3;
  wire LD_I3;
  output LD_SR;
  wire LD_SR;
  output LD_EN;
  wire LD_EN;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire E1BEG0_r;
  wire E1BEG1_r;
  wire E1BEG2_r;
  wire E1BEG3_r;
  wire J_EN_BEG0;
  wire J_EN_BEG0_r;
  wire J_EN_BEG1;
  wire J_EN_BEG1_r;
  wire J_EN_BEG2;
  wire J_EN_BEG2_r;
  wire J_EN_BEG3;
  wire J_EN_BEG3_r;
  wire J_EN_END0;
  wire J_EN_END1;
  wire J_EN_END2;
  wire J_EN_END3;
  wire J_SR_BEG0;
  wire J_SR_BEG0_r;
  wire J_SR_END0;
  wire LA_I0_r;
  wire LA_I1_r;
  wire LA_I2_r;
  wire LA_I3_r;
  wire LB_I0_r;
  wire LB_I1_r;
  wire LB_I2_r;
  wire LB_I3_r;
  wire LC_I0_r;
  wire LC_I1_r;
  wire LC_I2_r;
  wire LC_I3_r;
  wire LD_I0_r;
  wire LD_I1_r;
  wire LD_I2_r;
  wire LD_I3_r;
  wire N1BEG0_r;
  wire N1BEG1_r;
  wire N1BEG2_r;
  wire N1BEG3_r;
  wire S1BEG0_r;
  wire S1BEG1_r;
  wire S1BEG2_r;
  wire S1BEG3_r;
  wire W1BEG0_r;
  wire W1BEG1_r;
  wire W1BEG2_r;
  wire W1BEG3_r;
  sky130_fd_sc_hd__clkbuf_1 _068_ (
    .A(LC_O),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux4_2 _069_ (
    .A0(E1END2),
    .A1(LB_O),
    .A2(S1END2),
    .A3(_000_),
    .S0(cfg[8]),
    .S1(cfg[6]),
    .X(_001_)
  );
  sky130_fd_sc_hd__clkbuf_1 _070_ (
    .A(LD_O),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2i_1 _071_ (
    .A0(W1END2),
    .A1(_002_),
    .S(cfg[8]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkbuf_1 _072_ (
    .A(LA_O),
    .X(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _073_ (
    .A(_004_),
    .B(cfg[6]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__o221ai_1 _074_ (
    .A1(cfg[6]),
    .A2(_003_),
    .B1(_005_),
    .B2(cfg[8]),
    .C1(cfg[7]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__o21a_1 _075_ (
    .A1(cfg[7]),
    .A2(_001_),
    .B1(_006_),
    .X(N1BEG2)
  );
  sky130_fd_sc_hd__clkbuf_1 _076_ (
    .A(LB_O),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux4_2 _077_ (
    .A0(E1END3),
    .A1(S1END3),
    .A2(_007_),
    .A3(_000_),
    .S0(cfg[9]),
    .S1(cfg[11]),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2i_1 _078_ (
    .A0(W1END3),
    .A1(_002_),
    .S(cfg[11]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _079_ (
    .A(_004_),
    .B(cfg[9]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__o221ai_1 _080_ (
    .A1(cfg[9]),
    .A2(_009_),
    .B1(_010_),
    .B2(cfg[11]),
    .C1(cfg[10]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__o21a_1 _081_ (
    .A1(cfg[10]),
    .A2(_008_),
    .B1(_011_),
    .X(N1BEG3)
  );
  sky130_fd_sc_hd__mux4_2 _082_ (
    .A0(N1END0),
    .A1(S1END0),
    .A2(_007_),
    .A3(_000_),
    .S0(cfg[12]),
    .S1(cfg[14]),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2i_1 _083_ (
    .A0(W1END0),
    .A1(_002_),
    .S(cfg[14]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _084_ (
    .A(_004_),
    .B(cfg[12]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__o221ai_1 _085_ (
    .A1(cfg[12]),
    .A2(_013_),
    .B1(_014_),
    .B2(cfg[14]),
    .C1(cfg[13]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__o21a_1 _086_ (
    .A1(cfg[13]),
    .A2(_012_),
    .B1(_015_),
    .X(E1BEG0)
  );
  sky130_fd_sc_hd__mux4_2 _087_ (
    .A0(N1END1),
    .A1(S1END1),
    .A2(_007_),
    .A3(_000_),
    .S0(cfg[15]),
    .S1(cfg[17]),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2i_1 _088_ (
    .A0(W1END1),
    .A1(_002_),
    .S(cfg[17]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _089_ (
    .A(_004_),
    .B(cfg[15]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__o221ai_1 _090_ (
    .A1(cfg[15]),
    .A2(_017_),
    .B1(_018_),
    .B2(cfg[17]),
    .C1(cfg[16]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__o21a_1 _091_ (
    .A1(cfg[16]),
    .A2(_016_),
    .B1(_019_),
    .X(E1BEG1)
  );
  sky130_fd_sc_hd__mux4_2 _092_ (
    .A0(N1END2),
    .A1(LB_O),
    .A2(S1END2),
    .A3(_000_),
    .S0(cfg[20]),
    .S1(cfg[18]),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2i_1 _093_ (
    .A0(W1END2),
    .A1(_002_),
    .S(cfg[20]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _094_ (
    .A(_004_),
    .B(cfg[18]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__o221ai_1 _095_ (
    .A1(cfg[18]),
    .A2(_021_),
    .B1(_022_),
    .B2(cfg[20]),
    .C1(cfg[19]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__o21a_1 _096_ (
    .A1(cfg[19]),
    .A2(_020_),
    .B1(_023_),
    .X(E1BEG2)
  );
  sky130_fd_sc_hd__mux4_2 _097_ (
    .A0(N1END3),
    .A1(S1END3),
    .A2(_007_),
    .A3(_000_),
    .S0(cfg[21]),
    .S1(cfg[23]),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2i_1 _098_ (
    .A0(W1END3),
    .A1(_002_),
    .S(cfg[23]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _099_ (
    .A(_004_),
    .B(cfg[21]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o221ai_1 _100_ (
    .A1(cfg[21]),
    .A2(_025_),
    .B1(_026_),
    .B2(cfg[23]),
    .C1(cfg[22]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o21a_1 _101_ (
    .A1(cfg[22]),
    .A2(_024_),
    .B1(_027_),
    .X(E1BEG3)
  );
  sky130_fd_sc_hd__mux4_2 _102_ (
    .A0(N1END0),
    .A1(E1END0),
    .A2(_007_),
    .A3(_000_),
    .S0(cfg[24]),
    .S1(cfg[26]),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2i_1 _103_ (
    .A0(W1END0),
    .A1(_002_),
    .S(cfg[26]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _104_ (
    .A(_004_),
    .B(cfg[24]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__o221ai_1 _105_ (
    .A1(cfg[24]),
    .A2(_029_),
    .B1(_030_),
    .B2(cfg[26]),
    .C1(cfg[25]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__o21a_1 _106_ (
    .A1(cfg[25]),
    .A2(_028_),
    .B1(_031_),
    .X(S1BEG0)
  );
  sky130_fd_sc_hd__mux4_2 _107_ (
    .A0(N1END1),
    .A1(E1END1),
    .A2(_007_),
    .A3(_000_),
    .S0(cfg[27]),
    .S1(cfg[29]),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2i_1 _108_ (
    .A0(W1END1),
    .A1(_002_),
    .S(cfg[29]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _109_ (
    .A(_004_),
    .B(cfg[27]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o221ai_1 _110_ (
    .A1(cfg[27]),
    .A2(_033_),
    .B1(_034_),
    .B2(cfg[29]),
    .C1(cfg[28]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__o21a_1 _111_ (
    .A1(cfg[28]),
    .A2(_032_),
    .B1(_035_),
    .X(S1BEG1)
  );
  sky130_fd_sc_hd__mux4_2 _112_ (
    .A0(N1END2),
    .A1(LB_O),
    .A2(E1END2),
    .A3(_000_),
    .S0(cfg[32]),
    .S1(cfg[30]),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2i_1 _113_ (
    .A0(W1END2),
    .A1(_002_),
    .S(cfg[32]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _114_ (
    .A(_004_),
    .B(cfg[30]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__o221ai_1 _115_ (
    .A1(cfg[30]),
    .A2(_037_),
    .B1(_038_),
    .B2(cfg[32]),
    .C1(cfg[31]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__o21a_1 _116_ (
    .A1(cfg[31]),
    .A2(_036_),
    .B1(_039_),
    .X(S1BEG2)
  );
  sky130_fd_sc_hd__mux4_2 _117_ (
    .A0(N1END3),
    .A1(E1END3),
    .A2(_007_),
    .A3(LC_O),
    .S0(cfg[33]),
    .S1(cfg[35]),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2i_1 _118_ (
    .A0(W1END3),
    .A1(_002_),
    .S(cfg[35]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _119_ (
    .A(_004_),
    .B(cfg[33]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o221ai_1 _120_ (
    .A1(cfg[33]),
    .A2(_041_),
    .B1(_042_),
    .B2(cfg[35]),
    .C1(cfg[34]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o21a_1 _121_ (
    .A1(cfg[34]),
    .A2(_040_),
    .B1(_043_),
    .X(S1BEG3)
  );
  sky130_fd_sc_hd__mux4_2 _122_ (
    .A0(N1END0),
    .A1(E1END0),
    .A2(_007_),
    .A3(LC_O),
    .S0(cfg[36]),
    .S1(cfg[38]),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2i_1 _123_ (
    .A0(S1END0),
    .A1(LD_O),
    .S(cfg[38]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _124_ (
    .A(LA_O),
    .B(cfg[36]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o221ai_1 _125_ (
    .A1(cfg[36]),
    .A2(_045_),
    .B1(_046_),
    .B2(cfg[38]),
    .C1(cfg[37]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o21a_1 _126_ (
    .A1(cfg[37]),
    .A2(_044_),
    .B1(_047_),
    .X(W1BEG0)
  );
  sky130_fd_sc_hd__mux4_2 _127_ (
    .A0(N1END1),
    .A1(E1END1),
    .A2(_007_),
    .A3(LC_O),
    .S0(cfg[39]),
    .S1(cfg[41]),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2i_1 _128_ (
    .A0(S1END1),
    .A1(LD_O),
    .S(cfg[41]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _129_ (
    .A(LA_O),
    .B(cfg[39]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o221ai_1 _130_ (
    .A1(cfg[39]),
    .A2(_049_),
    .B1(_050_),
    .B2(cfg[41]),
    .C1(cfg[40]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o21a_1 _131_ (
    .A1(cfg[40]),
    .A2(_048_),
    .B1(_051_),
    .X(W1BEG1)
  );
  sky130_fd_sc_hd__mux4_2 _132_ (
    .A0(N1END2),
    .A1(LB_O),
    .A2(E1END2),
    .A3(LC_O),
    .S0(cfg[44]),
    .S1(cfg[42]),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2i_1 _133_ (
    .A0(S1END2),
    .A1(LD_O),
    .S(cfg[44]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _134_ (
    .A(LA_O),
    .B(cfg[42]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o221ai_1 _135_ (
    .A1(cfg[42]),
    .A2(_053_),
    .B1(_054_),
    .B2(cfg[44]),
    .C1(cfg[43]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o21a_1 _136_ (
    .A1(cfg[43]),
    .A2(_052_),
    .B1(_055_),
    .X(W1BEG2)
  );
  sky130_fd_sc_hd__mux4_2 _137_ (
    .A0(N1END3),
    .A1(E1END3),
    .A2(_007_),
    .A3(LC_O),
    .S0(cfg[45]),
    .S1(cfg[47]),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2i_1 _138_ (
    .A0(S1END3),
    .A1(LD_O),
    .S(cfg[47]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _139_ (
    .A(LA_O),
    .B(cfg[45]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o221ai_1 _140_ (
    .A1(cfg[45]),
    .A2(_057_),
    .B1(_058_),
    .B2(cfg[47]),
    .C1(cfg[46]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__o21a_1 _141_ (
    .A1(cfg[46]),
    .A2(_056_),
    .B1(_059_),
    .X(W1BEG3)
  );
  sky130_fd_sc_hd__mux4_2 _142_ (
    .A0(N1END0),
    .A1(E1END0),
    .A2(S1END0),
    .A3(W1END0),
    .S0(cfg[48]),
    .S1(cfg[49]),
    .X(LA_I0)
  );
  sky130_fd_sc_hd__mux4_2 _143_ (
    .A0(N1END1),
    .A1(E1END1),
    .A2(S1END1),
    .A3(W1END1),
    .S0(cfg[50]),
    .S1(cfg[51]),
    .X(LA_I1)
  );
  sky130_fd_sc_hd__mux4_2 _144_ (
    .A0(N1END2),
    .A1(E1END2),
    .A2(S1END2),
    .A3(W1END2),
    .S0(cfg[52]),
    .S1(cfg[53]),
    .X(LA_I2)
  );
  sky130_fd_sc_hd__mux4_2 _145_ (
    .A0(N1END3),
    .A1(E1END3),
    .A2(S1END3),
    .A3(W1END3),
    .S0(cfg[54]),
    .S1(cfg[55]),
    .X(LA_I3)
  );
  sky130_fd_sc_hd__mux4_2 _146_ (
    .A0(N1END0),
    .A1(E1END0),
    .A2(S1END0),
    .A3(W1END0),
    .S0(cfg[56]),
    .S1(cfg[57]),
    .X(LB_I0)
  );
  sky130_fd_sc_hd__mux4_2 _147_ (
    .A0(N1END1),
    .A1(E1END1),
    .A2(S1END1),
    .A3(W1END1),
    .S0(cfg[58]),
    .S1(cfg[59]),
    .X(LB_I1)
  );
  sky130_fd_sc_hd__mux4_2 _148_ (
    .A0(E1END1),
    .A1(W1END1),
    .A2(LB_O),
    .A3(LD_O),
    .S0(cfg[4]),
    .S1(cfg[5]),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2i_1 _149_ (
    .A0(S1END1),
    .A1(_000_),
    .S(cfg[5]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _150_ (
    .A(LA_O),
    .B(cfg[4]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o221ai_1 _151_ (
    .A1(cfg[4]),
    .A2(_061_),
    .B1(_062_),
    .B2(cfg[5]),
    .C1(cfg[3]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__o21a_1 _152_ (
    .A1(cfg[3]),
    .A2(_060_),
    .B1(_063_),
    .X(N1BEG1)
  );
  sky130_fd_sc_hd__mux4_2 _153_ (
    .A0(N1END2),
    .A1(E1END2),
    .A2(S1END2),
    .A3(W1END2),
    .S0(cfg[60]),
    .S1(cfg[61]),
    .X(LB_I2)
  );
  sky130_fd_sc_hd__mux4_2 _154_ (
    .A0(N1END3),
    .A1(E1END3),
    .A2(S1END3),
    .A3(W1END3),
    .S0(cfg[62]),
    .S1(cfg[63]),
    .X(LB_I3)
  );
  sky130_fd_sc_hd__mux4_2 _155_ (
    .A0(N1END0),
    .A1(E1END0),
    .A2(S1END0),
    .A3(W1END0),
    .S0(cfg[64]),
    .S1(cfg[65]),
    .X(LC_I0)
  );
  sky130_fd_sc_hd__mux4_2 _156_ (
    .A0(N1END1),
    .A1(E1END1),
    .A2(S1END1),
    .A3(W1END1),
    .S0(cfg[66]),
    .S1(cfg[67]),
    .X(LC_I1)
  );
  sky130_fd_sc_hd__mux4_2 _157_ (
    .A0(N1END2),
    .A1(E1END2),
    .A2(S1END2),
    .A3(W1END2),
    .S0(cfg[68]),
    .S1(cfg[69]),
    .X(LC_I2)
  );
  sky130_fd_sc_hd__mux4_2 _158_ (
    .A0(N1END3),
    .A1(E1END3),
    .A2(S1END3),
    .A3(W1END3),
    .S0(cfg[70]),
    .S1(cfg[71]),
    .X(LC_I3)
  );
  sky130_fd_sc_hd__mux4_2 _159_ (
    .A0(N1END0),
    .A1(E1END0),
    .A2(S1END0),
    .A3(W1END0),
    .S0(cfg[72]),
    .S1(cfg[73]),
    .X(LD_I0)
  );
  sky130_fd_sc_hd__mux4_2 _160_ (
    .A0(N1END1),
    .A1(E1END1),
    .A2(S1END1),
    .A3(W1END1),
    .S0(cfg[74]),
    .S1(cfg[75]),
    .X(LD_I1)
  );
  sky130_fd_sc_hd__mux4_2 _161_ (
    .A0(E1END0),
    .A1(S1END0),
    .A2(LB_O),
    .A3(LC_O),
    .S0(cfg[0]),
    .S1(cfg[2]),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2i_1 _162_ (
    .A0(W1END0),
    .A1(LD_O),
    .S(cfg[2]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _163_ (
    .A(LA_O),
    .B(cfg[0]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o221ai_1 _164_ (
    .A1(cfg[0]),
    .A2(_065_),
    .B1(_066_),
    .B2(cfg[2]),
    .C1(cfg[1]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__o21a_1 _165_ (
    .A1(cfg[1]),
    .A2(_064_),
    .B1(_067_),
    .X(N1BEG0)
  );
  sky130_fd_sc_hd__mux4_2 _166_ (
    .A0(N1END2),
    .A1(E1END2),
    .A2(S1END2),
    .A3(W1END2),
    .S0(cfg[76]),
    .S1(cfg[77]),
    .X(LD_I2)
  );
  sky130_fd_sc_hd__mux4_2 _167_ (
    .A0(N1END3),
    .A1(E1END3),
    .A2(S1END3),
    .A3(W1END3),
    .S0(cfg[78]),
    .S1(cfg[79]),
    .X(LD_I3)
  );
  sky130_fd_sc_hd__mux4_2 _168_ (
    .A0(N1END0),
    .A1(E1END0),
    .A2(S1END0),
    .A3(W1END0),
    .S0(cfg[80]),
    .S1(cfg[81]),
    .X(LA_SR)
  );
  sky130_fd_sc_hd__mux4_2 _169_ (
    .A0(N1END0),
    .A1(E1END0),
    .A2(S1END0),
    .A3(W1END0),
    .S0(cfg[82]),
    .S1(cfg[83]),
    .X(LA_EN)
  );
  sky130_fd_sc_hd__mux4_2 _170_ (
    .A0(N1END1),
    .A1(E1END1),
    .A2(S1END1),
    .A3(W1END1),
    .S0(cfg[84]),
    .S1(cfg[85]),
    .X(LB_EN)
  );
  sky130_fd_sc_hd__mux4_2 _171_ (
    .A0(N1END2),
    .A1(E1END2),
    .A2(S1END2),
    .A3(W1END2),
    .S0(cfg[86]),
    .S1(cfg[87]),
    .X(LC_EN)
  );
  sky130_fd_sc_hd__mux4_2 _172_ (
    .A0(N1END3),
    .A1(E1END3),
    .A2(S1END3),
    .A3(W1END3),
    .S0(cfg[88]),
    .S1(cfg[89]),
    .X(LD_EN)
  );
  assign J_EN_BEG3_r = LD_EN;
  assign J_EN_BEG2_r = LC_EN;
  assign J_EN_BEG1_r = LB_EN;
  assign J_EN_BEG0_r = LA_EN;
  assign J_SR_BEG0_r = LA_SR;
  assign LD_I3_r = LD_I3;
  assign LD_I2_r = LD_I2;
  assign LD_I1_r = LD_I1;
  assign LD_I0_r = LD_I0;
  assign LC_I3_r = LC_I3;
  assign LC_I2_r = LC_I2;
  assign LC_I1_r = LC_I1;
  assign LC_I0_r = LC_I0;
  assign LB_I3_r = LB_I3;
  assign LB_I2_r = LB_I2;
  assign LB_I1_r = LB_I1;
  assign LB_I0_r = LB_I0;
  assign LA_I3_r = LA_I3;
  assign LA_I2_r = LA_I2;
  assign LA_I1_r = LA_I1;
  assign LA_I0_r = LA_I0;
  assign W1BEG3_r = W1BEG3;
  assign W1BEG2_r = W1BEG2;
  assign W1BEG1_r = W1BEG1;
  assign W1BEG0_r = W1BEG0;
  assign S1BEG3_r = S1BEG3;
  assign S1BEG2_r = S1BEG2;
  assign S1BEG1_r = S1BEG1;
  assign S1BEG0_r = S1BEG0;
  assign E1BEG3_r = E1BEG3;
  assign E1BEG2_r = E1BEG2;
  assign E1BEG1_r = E1BEG1;
  assign E1BEG0_r = E1BEG0;
  assign N1BEG3_r = N1BEG3;
  assign N1BEG2_r = N1BEG2;
  assign N1BEG1_r = N1BEG1;
  assign N1BEG0_r = N1BEG0;
  assign J_SR_END0 = LA_SR;
  assign J_SR_BEG0 = LA_SR;
  assign J_EN_END3 = LD_EN;
  assign J_EN_END2 = LC_EN;
  assign J_EN_END1 = LB_EN;
  assign J_EN_END0 = LA_EN;
  assign J_EN_BEG3 = LD_EN;
  assign J_EN_BEG2 = LC_EN;
  assign J_EN_BEG1 = LB_EN;
  assign J_EN_BEG0 = LA_EN;
  assign LD_SR = LA_SR;
  assign LC_SR = LA_SR;
  assign LB_SR = LA_SR;
endmodule

module lut4_slice(clk, rst, ce, in, lut_init, reg_sel, out);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input ce;
  wire ce;
  input [3:0] in;
  wire [3:0] in;
  input [15:0] lut_init;
  wire [15:0] lut_init;
  input reg_sel;
  wire reg_sel;
  output out;
  wire out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire ff_q;
  sky130_fd_sc_hd__mux4_2 _09_ (
    .A0(lut_init[0]),
    .A1(lut_init[1]),
    .A2(lut_init[2]),
    .A3(lut_init[3]),
    .S0(in[0]),
    .S1(in[1]),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux4_2 _10_ (
    .A0(lut_init[8]),
    .A1(lut_init[9]),
    .A2(lut_init[10]),
    .A3(lut_init[11]),
    .S0(in[0]),
    .S1(in[1]),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux4_2 _11_ (
    .A0(lut_init[4]),
    .A1(lut_init[5]),
    .A2(lut_init[6]),
    .A3(lut_init[7]),
    .S0(in[0]),
    .S1(in[1]),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux4_2 _12_ (
    .A0(lut_init[12]),
    .A1(lut_init[13]),
    .A2(lut_init[14]),
    .A3(lut_init[15]),
    .S0(in[0]),
    .S1(in[1]),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux4_2 _13_ (
    .A0(_01_),
    .A1(_02_),
    .A2(_03_),
    .A3(_04_),
    .S0(in[3]),
    .S1(in[2]),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_2 _14_ (
    .A0(_05_),
    .A1(ff_q),
    .S(reg_sel),
    .X(out)
  );
  sky130_fd_sc_hd__inv_1 _15_ (
    .A(ce),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _16_ (
    .A(ff_q),
    .B(ce),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nor2_1 _17_ (
    .A(rst),
    .B(_07_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__o21a_1 _18_ (
    .A1(_06_),
    .A2(_05_),
    .B1(_08_),
    .X(_00_)
  );
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_00_),
    .Q(ff_q)
  );
endmodule
